### ISSUE TITLE
error when configuring for Windows

### ISSUE THREAD

**Issue by Someone65** [grejppi/bitrot#8]
When I do ./waf configure --platform win64 on Ubuntu, this happens:
`Traceback (most recent call last):
  File "/home/someone64/Downloads/bitrot/.waf-2.0.12-6cd57ca9068ebdd4dc6caef5723653c7/waflib/Scripting.py", line 119, in waf_entry_point
    run_commands()
  File "/home/someone64/Downloads/bitrot/.waf-2.0.12-6cd57ca9068ebdd4dc6caef5723653c7/waflib/Scripting.py", line 179, in run_commands
    ctx=run_command(cmd_name)
  File "/home/someone64/Downloads/bitrot/.waf-2.0.12-6cd57ca9068ebdd4dc6caef5723653c7/waflib/Scripting.py", line 170, in run_command
    ctx.execute()
  File "/home/someone64/Downloads/bitrot/.waf-2.0.12-6cd57ca9068ebdd4dc6caef5723653c7/waflib/Configure.py", line 85, in execute
    super(ConfigurationContext,self).execute()
  File "/home/someone64/Downloads/bitrot/.waf-2.0.12-6cd57ca9068ebdd4dc6caef5723653c7/waflib/Context.py", line 85, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/someone64/Downloads/bitrot/.waf-2.0.12-6cd57ca9068ebdd4dc6caef5723653c7/waflib/Context.py", line 126, in recurse
    user_function(self)
  File "/home/someone64/Downloads/bitrot/wscript", line 88, in configure
    conf.env.AR       = which(toolchain + 'ar')
  File "/home/someone64/Downloads/bitrot/wscript", line 22, in which
    if os.access(path, mode):
TypeError: coercing to Unicode: need string or buffer, NoneType found
`

Happens for both win64 and win32 but works fine for Linux.

**Comment by grejppi** [comment]
Hi, the error message looks rather cryptic indeed! It seems to be caused by the script not finding the right toolchain 🤔

The Windows targets are built with the [MinGW-w64](https://www.mingw-w64.org) toolchain, so please make sure it is installed and try again.

**Comment by grejppi** [comment]
Alternatively, you can try the Vagrant method (using a virtual machine) as described in the readme, if you find it's not too much trouble.

`Vagrantfile` contains the command to install all the possible build dependencies on Ubuntu in its provisioning script in any case.

**Comment by Someone65** [comment]
Yeah... I really should've been paying attention lol. I saw the contents of the Vagrantfile before even posting this report which installs the dependencies and should've copied those commands over. Installing mingw-w64 did indeed actually fix it! Sorry for the trouble.
